//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public Libro()
        {
            this.Prestamoes = new HashSet<Prestamo>();
        }
    
        public int IdLibro { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Titulo { get; set; }
        public string ISBN { get; set; }
        public string Editorial { get; set; }
        public Nullable<byte> NumPags { get; set; }
        public Nullable<int> IdAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual ICollection<Prestamo> Prestamoes { get; set; }
    }
}
